spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    #driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: tao
    password: 123456
    url: jdbc:oracle:thin:@localhost:46333:XE
    #url: jdbc:p6spy:oracle:thin:@localhost:46333:XE
  sql:
    init:
      schema-locations: classpath:db/oracle.sql
      #mode: always